title: Quan Huang's Homepage
page-top-title: 黄全的个人主页
top-section-bg-text: Computer Science
home-subtitle: Quan Huang&ensp;|&ensp;黄全
copyright-text: '&copy; Quan Huang 2023-2025. All Rights Reserved.'
